### Notion Databaseのデータを取得
POST https://api.notion.com/v1/databases/98f510c9fe0a4b3abcfa0bd21393b8ff/query
Authorization: Bearer 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
Notion-Version: 2022-06-28
Content-Type: application/json

{
    "filter": {
        "property": "Status",
        "status": {
            "equals": "Not Done"
        }
    },
    "sorts": [
        {
            "property": "Deadline",
            "direction": "descending"
        }
    ]
}

### Notion Databaseのデータを取得
POST https://api.notion.com/v1/databases/98f510c9fe0a4b3abcfa0bd21393b8ff/query
Authorization: Bearer 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
Notion-Version: 2022-06-28
Content-Type: application/json

{
    "filter": {
        "and": [
            {
                "property": "Status",
                "status": {
                    "equals": "Not Done"
                }
            },
            {
                "property": "Tag",
                "multi_select": {
                    "contains": "To Do"
                }
            }
        ]
    },
    "sorts": [
        {
            "property": "Deadline",
            "direction": "descending"
        }
    ]
}

### Notion Database(Todo for Work)
POST https://api.notion.com/v1/databases/d69d416106414204b982ef49e61b301b/query
Authorization: Bearer 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
Notion-Version: 2022-06-28
Content-Type: application/json

{
    "filter": {
        "and": [
            {
                "or": [
                    {
                        "property": "Status",
                        "status": {
                            "equals": "未着手"
                        }
                    },
                    {
                        "property": "Status",
                        "status": {
                            "equals": "進行中"
                        }
                    }
                ]
            },
            {
                "property": "Deadline",
                "date": {
                    "on_or_before": "2025-06-09"
                }
            }
        ]
    },
    "sorts": [
        {
            "property": "Deadline",
            "direction": "descending"
        }
    ]
}


###
POST https://api.notion.com/v1/databases/98f510c9fe0a4b3abcfa0bd21393b8ff/query
Authorization: Bearer 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
Notion-Version: 2022-06-28
Content-Type: application/json

{
    "filter": {
        "or": [
            {
                "and": [
                    {
                        "property": "Status",
                        "status": {
                            "equals": "Not Done"
                        }
                    },
                    {
                        "property": "Priority",
                        "select": {
                            "equals": "1"
                        }
                    },
                    {
                        "property": "Deadline",
                        "date": {
                            "is_not_empty": true
                        }
                    },
                    {
                        "property": "サブアイテム",
                        "relation": {
                            "is_empty": true
                        }
                    }
                ]
            },
            {
                "and": [
                    {
                        "property": "Status",
                        "status": {
                            "equals": "Not Done"
                        }
                    },
                    {
                        "property": "Priority",
                        "select": {
                            "equals": "2"
                        }
                    },
                    {
                        "property": "Deadline",
                        "date": {
                            "is_not_empty": true
                        }
                    },
                    {
                        "property": "サブアイテム",
                        "relation": {
                            "is_empty": true
                        }
                    }
                ]
            },
            {
                "and": [
                    {
                        "property": "Status",
                        "status": {
                            "equals": "Not Done"
                        }
                    },
                    {
                        "property": "Priority",
                        "select": {
                            "equals": "3"
                        }
                    },
                    {
                        "property": "Deadline",
                        "date": {
                            "is_not_empty": true
                        }
                    },
                    {
                        "property": "サブアイテム",
                        "relation": {
                            "is_empty": true
                        }
                    }
                ]
            },
            {
                "and": [
                    {
                        "property": "Status",
                        "status": {
                            "equals": "On Going"
                        }
                    },
                    {
                        "property": "Priority",
                        "select": {
                            "equals": "1"
                        }
                    },
                    {
                        "property": "Deadline",
                        "date": {
                            "is_not_empty": true
                        }
                    },
                    {
                        "property": "サブアイテム",
                        "relation": {
                            "is_empty": true
                        }
                    }
                ]
            },
            {
                "and": [
                    {
                        "property": "Status",
                        "status": {
                            "equals": "On Going"
                        }
                    },
                    {
                        "property": "Priority",
                        "select": {
                            "equals": "2"
                        }
                    },
                    {
                        "property": "Deadline",
                        "date": {
                            "is_not_empty": true
                        }
                    },
                    {
                        "property": "サブアイテム",
                        "relation": {
                            "is_empty": true
                        }
                    }
                ]
            },
            {
                "and": [
                    {
                        "property": "Status",
                        "status": {
                            "equals": "On Going"
                        }
                    },
                    {
                        "property": "Priority",
                        "select": {
                            "equals": "3"
                        }
                    },
                    {
                        "property": "Deadline",
                        "date": {
                            "is_not_empty": true
                        }
                    },
                    {
                        "property": "サブアイテム",
                        "relation": {
                            "is_empty": true
                        }
                    }
                ]
            }
        ]
    },
    "sorts": [
        {
            "property": "Deadline",
            "direction": "ascending"
        },
        {
            "property": "Priority",
            "direction": "ascending"
        },
        {
            "property": "Created_At",
            "direction": "ascending"
        }
    ]
}

